version: "3.0"

services:
  nms:
    image: asesha68/nms:1.0.24
    command: >
      bash -c
         "python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          gunicorn --bind 0.0.0.0:8000 nms_project_settings.wsgi:application --access-logile &&
          python manage.py collectstatic --noinput "

    network_mode: "host"
    volumes:
      - ./app/databases:/home/ubuntu/nms_project/database
      - /app/static:/app/static
      - /home/ubuntu:/home/ubuntu
      - /app/docker_pipes:/app/docker_pipes
